services:
  mysql:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    volumes:
      - /data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=car
      - MYSQL_PASSWORD=root
  redis:
    image: redis:bullseye
    ports:
      - "6379:6379"
